name: Vercel Deploy (prebuilt)

on:
  push:
    branches: [ master ]
    paths:
      - src/**
      - public/**
      - package.json
      - vercel.json
      - next.config.js
      - tailwind.config.js
      - postcss.config.js
      - tsconfig.json
  pull_request:

  # add manual trigger to deploy
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
        if: github.event_name == 'pull_request'

      - name: Pull Vercel Environment Information (Production)
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        if: github.ref == 'refs/heads/master'

      - name: Build Project Artifacts (Preview)
        run: vercel build --token=$VERCEL_TOKEN
        if: github.event_name == 'pull_request'

      - name: Build Project Artifacts (Production)
        run: vercel build --prod --token=$VERCEL_TOKEN
        if: github.ref == 'refs/heads/master'

      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        run: vercel deploy --prebuilt --yes --token=$VERCEL_TOKEN

      - name: Deploy Production
        if: github.ref == 'refs/heads/master'
        run: vercel deploy --prebuilt --prod --yes --token=$VERCEL_TOKEN
